<?xml version="1.0" encoding="utf-8"?><testsuites name="pytest tests"><testsuite name="pytest" errors="1" failures="0" skipped="0" tests="1" time="3.926" timestamp="2025-07-22T16:47:22.308823+02:00" hostname="DESKTOP-0C1EB3V"><testcase classname="" name="tests.utils.test_helpers" time="0.000"><error message="collection failure">ImportError while importing test module 'C:\Users\user\OneDrive\Documents\capstone\repo\SAMFMS\tests\utils\test_helpers.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\importlib\__init__.py:88: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tests\utils\test_helpers.py:19: in &lt;module&gt;
    from tests.config.test_config import get_test_config, get_test_fixtures
E   ModuleNotFoundError: No module named 'tests.config'</error></testcase></testsuite></testsuites>